GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/1

###
POST  http://localhost:3000/api/users
content-type: application/json

{
    "first_name": "ALDRICH",
    "last_name": "SANTIAGO",
    "middle_name": "LINSANGAN",
    "role_id": 1,
    "status": "ACTIVE"
}

###
PUT http://localhost:3000/api/users/1

###
DELETE  http://localhost:3000/api/users/1